# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'desafio-ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for desafio-ios
  pod 'AFNetwork'
  pod 'Mantle'
  pod 'SDWebImage', '~> 4.0'
  pod 'TSMarkdownParser'

  target 'desafio-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
